services:
  postgres:
    container_name: nocharge-postgres
    image: postgres:18
    ports:
      - "5433:5432"
    volumes:
      - nocharge-postgres:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - DEBUG=true

  redis:
    container_name: nocharge-redis
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - nocharge-redis:/data

volumes:
  nocharge-postgres:
  nocharge-redis:
